name: On Template

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: On use template

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Replace if on template
        run: node ./on-template.js

      - name: Commit
        uses: actions-x/commit@v5
        with:
          name: 'Replace template variables'
          force: true
          branch: 'main'
